#!/usr/bin/env perl

use lib 'lib';
use v5.10;
use strict;
use warnings;
use Data::Dumper;
use Lifter;

if(-f $ARGV[0]) {
  my $world = Lifter::load_world(shift @ARGV);
  while(1) {
    Lifter::print_map $world;
    print "Enter move: ";
    my $move = <>;
    chomp $move;
    $world = Lifter::robot_move($world, $move);
    $world = Lifter::check_ending($world);
    $world = Lifter::world_update($world);
    $world = Lifter::check_ending($world);
  }
} else {
  # Contest-mode
  my $map = Lifter::load_map(\*STDIN);
  # ...
}

