#!/usr/bin/env perl

use lib '../lib';
use v5.10;
use strict;
use warnings;
use Data::Dumper;
use Lifter;

my $input = shift @ARGV;

my $world = Lifter::json_to_world($input, 1);




my $count = 0;
while ($count < 0) {
$count++;
open(my $file, '>>', 'log.txt') ; print $file "log message\n";

}


print "R";




# my $move = int (rand(4));
# if ($move == 0) { print 'U'; }
# if ($move == 1) { print 'D'; }
# if ($move == 2) { print 'L'; }
# if ($move == 3) { print 'R'; }

sub find_closest {
my $world = shift;

f

return $coord;

}